name: Build Chain

on: [pull_request]

jobs:
  build-chain:
    strategy:
      matrix:
        java-version: [8]
    runs-on: ubuntu-latest
    name: Maven Build
    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: Build Chain ${{ matrix.java-version }}
      id: build-chain
      uses: kiegroup/github-action-build-chain@BXMSPROD-981
      with:
        parent-dependencies: 'kie-jpmml-integration'
        child-dependencies: 'openshift-drools-hacep'
        build-command: 'mvn -e -nsu -Dfull -Pwildfly clean install -Pjenkins-pr-builder -Prun-code-coverage  -Dcontainer.profile=wildfly -Dcontainer=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -DjvmArgs="-Xms1g -Xmx5g -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:gclog"'
        build-command-upstream: "mvn -e -T1C clean install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true"
        workflow-file-name: "pull_request.yml"
        archive-artifacts-path: |
          **/gclog
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"          
                            