on: [pull_request]

jobs:
  build-chain:
    runs-on: ubuntu-latest
    name: Build Pull Request
    steps:
    - uses: actions/checkout@v2
    - name: Build Chain
      id: build-chain
      uses: kiegroup/github-action-build-chain@master
      with:
        parent-dependencies: 'kie-jpmml-integration'
        child-dependencies: 'openshift-drools-hacep'
        build-command: 'mvn -e -nsu -Dfull -Pwildfly clean install -Pjenkins-pr-builder -Prun-code-coverage  -Dcontainer.profile=wildfly -Dcontainer=wildfly -Dintegration-tests=true -Dmaven.test.failure.ignore=true -DjvmArgs="-Xms1g -Xmx5g -XX:+PrintGCDetails -XX:+PrintGCDateStamps -Xloggc:gclog" | mvn -nsu generate-resources -Psonarcloud-analysis -DjvmArgs="-Xms1g -Xmx4g"'
        build-command-upstream: "mvn -e -T1C clean install -DskipTests -Dgwt.compiler.skip=true -Dgwt.skipCompilation=true -Denforcer.skip=true -Dcheckstyle.skip=true -Dspotbugs.skip=true -Drevapi.skip=true"
      env:
          GITHUB_TOKEN: "${{ secrets.KIE_TOKEN }}"
